add_rules("mode.release", "mode.debug")
includes("../AMGPCG_Pybind_Torch/common/xmake.lua")
includes("../AMGPCG_Pybind_Torch/solver/xmake.lua")
includes("../engine/xmake.lua")
target("ofm")
    add_rules("plugin.vsxmake.autoupdate")
    set_policy("build.intermediate_directory", false)
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cu")
    add_includedirs(".",{public=true})
    add_cugencodes("compute_75")
    add_cuflags("--std c++17", "-lineinfo")
    add_deps("common")
    add_deps("solver")
    add_deps("engine")
